USE [dbEstudos]

CREATE TABLE PESSOA (
	PESSOAID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	DATANASC DATETIME NOT NULL,
	TELEFONE VARCHAR(15),
	ENDERECO VARCHAR(50),
	CEP VARCHAR(10),
);

CREATE TABLE CURSO (
	CURSOID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	--PESSOAID INT,
	CURSONOME VARCHAR(30) NOT NULL,
	DATACONCLUSAO DATETIME NOT NULL
);

--ALTER TABLE CURSO
--	ADD CONSTRAINT FK_PESSOA_CURSO FOREIGN KEY (PESSOAID)
--	REFERENCES PESSOA (PESSOAID);
	

CREATE TABLE PESSOA_CURSO(
	PESSOAID int NOT NULL,
	CURSOID int NOT NULL,
);

ALTER TABLE PESSOA_CURSO 
	ADD CONSTRAINT FK_PESSOA_CURSO_CURSO_CURSOID FOREIGN KEY(CURSOID)
	REFERENCES CURSO (CURSOID);

ALTER TABLE PESSOA_CURSO 
	ADD  CONSTRAINT PESSOA_CURSO_PESSOA_PESSOAID FOREIGN KEY(PESSOAID)
	REFERENCES PESSOA (PESSOAID)




